version: '3'

networks:
  gatonet:
    driver: bridge
    name: gatonet

volumes:
  postgres-data:
    name: postgres-data

services:
  app:
    build:
      context: ./
    image: arnaudsa/sample-app-dev
    entrypoint: dockerize -wait tcp://db:5432 -wait http://nginx:80 -timeout 30s docker-entrypoint.sh
    container_name: app
    ports:
      - "3000:3000"
    networks: 
      - gatonet
    depends_on:
      - db
  nginx:
    image: nginx:1.23.0
    container_name: nginx
    tty: true
    restart: always
    networks:
      - gatonet
    ports:
      - 8080:80  
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - app  
  db:
    image: postgres:13-alpine
    container_name: db
    restart: always
    tty: true
    networks:
      - gatonet
    volumes:
      - postgres-data:/var/lib/postgresql/data/pgdata
    environment:
      - POSTGRES_DB=sampledb
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
  adminer:
    image: adminer
    container_name: adminer
    restart: always
    networks:
      - gatonet
    depends_on:
      - db
    ports:
      - 8181:8080

